/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-12-07 20:59:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("   <title>투어메이트</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        div { font-family: \"함초롬돋움\"; }\r\n");
      out.write("\r\n");
      out.write("        div.header1 {\r\n");
      out.write("            width: 30%;\r\n");
      out.write("            float: left;\r\n");
      out.write("            margin-left: 25px;\r\n");
      out.write("            margin-top: 50px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        div.header2 {\r\n");
      out.write("            width: 33%;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("            float: left;\r\n");
      out.write("            margin-left: 25px;\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("            color: black;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("         div.header2 > a {\r\n");
      out.write("           color:black; text-decoration:none;\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("        div.header3 {\r\n");
      out.write("            width: 31%;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            float: left;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            margin-top: 65px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menubar {\r\n");
      out.write("          background: #FF8000;\r\n");
      out.write("          display: inline-block;\r\n");
      out.write("           width: 100%;\r\n");
      out.write("      }\r\n");
      out.write("      .main { margin: 0; padding: 0; font-size: 19px; }\r\n");
      out.write("      .main li {\r\n");
      out.write("         padding:0% 3% 0% 3%;\r\n");
      out.write("           float: left;\r\n");
      out.write("           list-style:none;\r\n");
      out.write("           position: relative;\r\n");
      out.write("      }\r\n");
      out.write("      .main li:first-child { margin-left: 10%; }\r\n");
      out.write("      .main li:hover { background: #984807; }\r\n");
      out.write("      .main a {\r\n");
      out.write("           color: white;\r\n");
      out.write("           display: block;\r\n");
      out.write("           padding: 10px 20px;\r\n");
      out.write("           text-decoration: none;\r\n");
      out.write("      }\r\n");
      out.write("      .main ul {\r\n");
      out.write("           background: white;\r\n");
      out.write("           display: none;\r\n");
      out.write("           padding: 0;\r\n");
      out.write("           position: absolute;\r\n");
      out.write("           left: 0;\r\n");
      out.write("           top: 100%;\r\n");
      out.write("           z-index: 2;\r\n");
      out.write("           width: 210px;\r\n");
      out.write("      }\r\n");
      out.write("      .main ul li { float: none; margin-left: 10%; }\r\n");
      out.write("      .main ul a { color: #984807; }\r\n");
      out.write("      .main ul li:hover { background: white; }\r\n");
      out.write("      .main ul li:hover>a { color: #FF8000; }\r\n");
      out.write("      \r\n");
      out.write("      .header3_button{\r\n");
      out.write("         float:left;\r\n");
      out.write("         border-right:2px solid black;\r\n");
      out.write("         padding-right:10px;\r\n");
      out.write("         margin-right:10px;\r\n");
      out.write("         font-size: 3;\r\n");
      out.write("      }\r\n");
      out.write("      .header3_button:first-child{ margin-left: 30%; }\r\n");
      out.write("      .header3_button:nth-child(2){cursor:pointer; }               \r\n");
      out.write("      .header3_button:last-child{ border-right: none; }\r\n");
      out.write("      .header3_button > a { color: black; text-decoration: none; }\r\n");
      out.write("\r\n");
      out.write("   </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"header1\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <a href=\"투어메이트.jsp\">\r\n");
      out.write("    <div class=\"header2\">\r\n");
      out.write("        <center>\r\n");
      out.write("            <font face=\"HYHeadLine\" size=\"7\">Tourmate</font><br>\r\n");
      out.write("            <font face=\"함초롬돋움\" size=\"4\">믿을 수 있는 여행 친구, 투어메이트</font>\r\n");
      out.write("        </center>\r\n");
      out.write("    </div>\r\n");
      out.write("    </a>\r\n");
      out.write("    <div class=\"header3\">\r\n");
      out.write("    ");

    // 현재 로그인된 아이디가 없다면 (= session에 저장된 id가 없다면)
    if(session.getAttribute("id") == null) {
    
      out.write("\r\n");
      out.write("      <div class=\"header3_button\"><a href=\"Login.jsp\">로그인</a></div>\r\n");
      out.write("      <div class=\"header3_button\"><a href=\"Signup.jsp\">회원가입</a></div>       \r\n");
      out.write("    ");
 } 
    // 현재 로그인된 아이디가 있다면 (= session에 저장된 id가 있다면)
    else { 
      out.write("\r\n");
      out.write("       <div class=\"header3_button\">");
      out.print( session.getAttribute("id") );
      out.write("님</div>\r\n");
      out.write("      <div class=\"header3_button\"><a href=\"Logout.jsp\">로그아웃</a></div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("  \r\n");
      out.write("      <div class=\"header3_button\"><a href=\"투어메이트.jsp#event\">이벤트</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!--상단 메뉴바와 하위 메뉴-->\r\n");
      out.write("    <script src=\"//code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("   <script>\r\n");
      out.write("   $(function(){\r\n");
      out.write("        $(\".main li\").hover(function(){\r\n");
      out.write("          $('ul:first',this).show();\r\n");
      out.write("        }, function(){\r\n");
      out.write("          $('ul:first',this).hide();\r\n");
      out.write("        });\r\n");
      out.write("   });\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("    <div class=\"menubar\">\r\n");
      out.write("        <ul class=\"main\">\r\n");
      out.write("            <li>\r\n");
      out.write("                 <a href=\"#\">여행 정보</a>\r\n");
      out.write("                 <ul>\r\n");
      out.write("                  <li><a href=\"인기_여행_도시.jsp\">인기 여행 도시</a></li>\r\n");
      out.write("                  <li><a href=\"여행_준비.jsp\">여행 준비</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">커뮤니티 </a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"여행_후기.jsp\">여행 후기</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">티켓/투어</a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"티켓투어_한국.jsp\">한국</a></li>\r\n");
      out.write("                    <li><a href=\"티켓투어_홍콩.jsp\">홍콩</a></li>\r\n");
      out.write("                    <li><a href=\"티켓투어_일본.jsp\">일본</a></li>\r\n");
      out.write("                    <li><a href=\"티켓투어_싱가포르.jsp\">싱가포르</a></li>\r\n");
      out.write("                    <li><a href=\"티켓투어_대만.jsp\">대만</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <li><a href=\"항공.jsp\">항공</a></li>\r\n");
      out.write("            <li><a href=\"호텔.jsp\">호텔</a></li>\r\n");
      out.write("            <li><a href=\"렌터카.jsp\">렌터카</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
