/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-12-07 08:57:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_005fsuccess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("   <title>투어메이트</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        div { font-family: \"함초롬돋움\"; }\r\n");
      out.write("      \r\n");
      out.write("      .titlebox {\r\n");
      out.write("         float:left;\r\n");
      out.write("         margin:3% 5% 3% 5%;\r\n");
      out.write("         width:15%;\r\n");
      out.write("         border-top:2px solid black;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      div.loginbox {\r\n");
      out.write("         float:left;\r\n");
      out.write("         border:1px solid #ddd;\r\n");
      out.write("         margin: 3% 3% 3% 10%;\r\n");
      out.write("         padding:0% 2% 0% 2%;\r\n");
      out.write("         width:auto;\r\n");
      out.write("         height:60%;\r\n");
      out.write("         color: #984807;\r\n");
      out.write("         font-size:30px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      input.button_logout{\r\n");
      out.write("         float:right;\r\n");
      out.write("         margin: 4% 4% 4% 0%;\r\n");
      out.write("         padding: 2% 3% 2% 3%;\r\n");
      out.write("         width:20%;\r\n");
      out.write("         height:30%;\r\n");
      out.write("         border-color:transparent;\r\n");
      out.write("         font-weight: 600;\r\n");
      out.write("         font-size: 17px;\r\n");
      out.write("         background: #FF8000;\r\n");
      out.write("         color: white;      \r\n");
      out.write("      }\r\n");
      out.write("   </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <!-- 제목+메뉴바를 포함한 Header.jsp 파일을 include -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <div class=\"titlebox\">\r\n");
      out.write("      <font size=20 style=\"bold\">LOGIN</font><br>\r\n");
      out.write("      <b>로그인</b>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- \r\n");
      out.write("   //check.jsp에서 지정한 세션 속성명 id 에서 값을 가져온 다음 값이 존재하지 않으면 logout.jsp로 넘어감\r\n");
      out.write("    if (session.getAttribute(\"id\") == null) {\r\n");
      out.write("        response.sendRedirect(\"Logout.jsp\");\r\n");
      out.write("    }\r\n");
      out.write("    -->\r\n");
      out.write("   <div class=\"loginbox\">\r\n");
      out.write("   <center>\r\n");
      out.write("   <!-- 값이 존재한다면 그 값을 출력한다 -->\r\n");
      out.write("   <p><b><font color=\"#FF8000\">");
      out.print( session.getAttribute("id") );
      out.write("</font></b><small>님 반갑습니다.</small></p>\r\n");
      out.write("   <p>당신의 여행 친구, 투어메이트입니다.</p>\r\n");
      out.write("   </center>\r\n");
      out.write("   <!-- logout.jsp로 하이퍼링크를 건 다음 클릭하면 페이지 이동 -->\r\n");
      out.write("   <a href=\"Logout.jsp\">\r\n");
      out.write("      <input type=\"button\" class=\"button_logout\" value=\"로그아웃\">\r\n");
      out.write("   </a>\r\n");
      out.write("   \r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <!-- 회사 정보와 약속을 포함한 Footer.jsp 파일을 include -->\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
