/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-12-07 13:50:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class 투어메이트_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("   <title>투어메이트</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        div { font-family: \"함초롬돋움\"; }\r\n");
      out.write("\r\n");
      out.write("        #best {\r\n");
      out.write("            width: 30%;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            float: left;\r\n");
      out.write("            background-color: #F2F2F2;\r\n");
      out.write("            margin: 0% 1.5% 3% 1.5%;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #best2 {\r\n");
      out.write("            width: 35%;\r\n");
      out.write("            height: 350px;\r\n");
      out.write("            float: left;\r\n");
      out.write("            background-color: #F2F2F2;\r\n");
      out.write("            margin: 0% 7% 3% 7%;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #best3 {\r\n");
      out.write("            width: 35%;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            float: left;\r\n");
      out.write("            background-color: #F2F2F2;\r\n");
      out.write("            margin: 0% 7% 3% 7%;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #best_korname {\r\n");
      out.write("            font-size: 3;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            color: black;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #best_engname {\r\n");
      out.write("            font-size: 3;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            color: gray;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #best_price {\r\n");
      out.write("            font-size: 3;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            color: gray;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #best_price2 {\r\n");
      out.write("            font-size: 3;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #aus_image {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 250px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #box {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 720px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #box2 {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 220px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #box3 {\r\n");
      out.write("            width: 40%;\r\n");
      out.write("            height: 45px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #box4 {\r\n");
      out.write("            width: 30%;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            padding: 10px 10px 10px 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #box5 {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 230px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #box6 {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 55px;\r\n");
      out.write("            background-color: #424242;\r\n");
      out.write("            color: white;\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("            padding-top: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #recommand1 {\r\n");
      out.write("            width: 46.5%;\r\n");
      out.write("            height: 250px;\r\n");
      out.write("            padding: 10px 20px 10px 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #recommand2 {\r\n");
      out.write("            width: 30%;\r\n");
      out.write("            height: 250px;\r\n");
      out.write("            padding: 10px 20px 10px 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .cycle-slideshow { z-index: 1; }\r\n");
      out.write("\r\n");
      out.write("        .cycle-pager {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cycle-pager span {\r\n");
      out.write("            font-size: 50px;\r\n");
      out.write("            width: 16px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            color: #ddd;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cycle-pager span.cycle-pager-active { color: #FF8000; }\r\n");
      out.write("        .cycle-pager > * { cursor: pointer; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <!-- 제목+메뉴바를 포함한 Header.jsp 파일을 include -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- 이미지 슬라이드 -->\r\n");
      out.write("    <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"http://malsup.github.com/jquery.cycle2.js\"></script>\r\n");
      out.write("    <div class=\"cycle-slideshow\" cycle-slideshow data-cycle-loader=\"wait\" data-cycle-timeout=1000>\r\n");
      out.write("        <div class=\"cycle-pager\"></div>\r\n");
      out.write("        <img id=\"box\" src=\"main/배경사진.png\">\r\n");
      out.write("        <img id=\"box\" src=\"main/배경사진4.jpg\">\r\n");
      out.write("        <img id=\"box\" src=\"main/배경사진3.jpg\">\r\n");
      out.write("        <img id=\"box\" src=\"main/배경사진2.png\">\r\n");
      out.write("        <img id=\"box\" src=\"main/배경사진5.jpg\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <br><br><br>\r\n");
      out.write("    <a name=\"event\">\r\n");
      out.write("    <font face=\"함초롬돋움\" size=\"7\"> BEST DEAL </font>\r\n");
      out.write("    <font face=\"함초롬돋움\" size=\"5\"> 추천 여행상품 정보</font>\r\n");
      out.write("    <br><br>\r\n");
      out.write("    <div id=\"best\" onclick=\"location.href='main_img1.jsp'\">\r\n");
      out.write("        <img id=\"box2\" src=\"main/포시즌스 호텔 서울.jpg\">\r\n");
      out.write("        <div id=\"best_korname\"> 포시즌스 호텔 서울 </div>\r\n");
      out.write("        <div id=\"best_engname\"> Four Seasons Hotel Seoul </div>\r\n");
      out.write("        <div id=\"best_price\">\r\n");
      out.write("            하루 <font color=\"red\" size=\"5\"><b>344,250</b></font>원\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"best\" onclick=\"location.href='main_img2.jsp'\">\r\n");
      out.write("        <img id=\"box2\" src=\"main/힐튼 괌.jpg\">\r\n");
      out.write("        <div id=\"best_korname\"> 힐튼 괌 리조트&스파 </div>\r\n");
      out.write("        <div id=\"best_engname\"> Hilton Guam Resort&Spa </div>\r\n");
      out.write("        <div id=\"best_price\">\r\n");
      out.write("            하루 <font color=\"red\" size=\"5\"><b>171,802</b></font>원\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"best\" onclick=\"location.href='main_img3.jsp'\">\r\n");
      out.write("        <img id=\"box2\" src=\"main/샌프란시스코 다리.jpg\">\r\n");
      out.write("        <div id=\"best_korname\"> 인천 (ICN) ⇌ 샌프란시스코 (SFO) </div>\r\n");
      out.write("        <div id=\"best_price\">\r\n");
      out.write("            <img id=\"box3\" src=\"main/아시아나 로고.png\" align=\"left\"><br>\r\n");
      out.write("            최저 <font color=\"red\" size=\"5\"><b>632,200</b></font>원\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <br>\r\n");
      out.write("    <div id=\"best\" onclick=\"location.href='main_img4.jsp'\">\r\n");
      out.write("        <img id=\"box2\" src=\"main/다낭.png\">\r\n");
      out.write("        <div id=\"best_korname\"> 인천 (ICN) ⇌ 다낭 (DAD) </div>\r\n");
      out.write("        <div id=\"best_price\">\r\n");
      out.write("            <img id=\"box4\" src=\"main/티웨이 로고.png\" align=\"left\"><br>\r\n");
      out.write("            최저 <font color=\"red\" size=\"5\"><b>368,700</b></font>원\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"best\" onclick=\"location.href='main_img5.jsp'\">\r\n");
      out.write("        <img id=\"box2\" src=\"main/자동차1.png\">\r\n");
      out.write("        <div id=\"best_korname\"> Toyota Corolla </div>\r\n");
      out.write("        <div id=\"best_engname\"> [호주]멜버른 </div>\r\n");
      out.write("        <div id=\"best_price\">\r\n");
      out.write("            하루 <font color=\"red\" size=\"5\"><b>36,080</b></font>원\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"best\" onclick=\"location.href='main_img6.jsp'\">\r\n");
      out.write("        <img id=\"box2\" src=\"main/유니버셜 재팬.jpg\">\r\n");
      out.write("        <div id=\"best_korname\"> [일본] 유니버셜 스튜디오 재팬 입장권 </div>\r\n");
      out.write("        <div id=\"best_engname\"> Universal Studios Japan Ticket 1 Day Pass </div>\r\n");
      out.write("        <div id=\"best_price\">\r\n");
      out.write("            ￥7,786 > <font color=\"red\" size=\"5\"><b> 78,200원</b></font>(￥7,786)\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <br><br>\r\n");
      out.write("    <font face=\"함초롬돋움\" size=\"7\"> HOT DEAL </font>\r\n");
      out.write("    <font face=\"함초롬돋움\" size=\"5\"> 여행상품 특가&할인쿠폰</font>\r\n");
      out.write("    <br><br>\r\n");
      out.write("    <div id=\"best2\" onclick=\"location.href='main_img7.jsp'\">\r\n");
      out.write("        <img id=\"box5\" src=\"main/폴란드 항공.jpg\">\r\n");
      out.write("        <div id=\"best_korname\"> [LOT 폴란드항공] 한국 취항 1주년 특가 판매 </div>\r\n");
      out.write("        <div id=\"best_price\">\r\n");
      out.write("            남은 시간 <font color=\"red\" size=\"5\"><b>10일</b></font>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"box6\">\r\n");
      out.write("            폴란드, 바르샤바, 오슬로<br>\r\n");
      out.write("            <div id=\"best_price2\">\r\n");
      out.write("                <font size=\"5\"><b> >  724,400 </b></font>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"best2\" onclick=\"location.href='main_img8.jsp'\">\r\n");
      out.write("        <img id=\"box5\" src=\"main/마카오.jpg\">\r\n");
      out.write("        <div id=\"best_korname\"> [씨트립] 마카오호텔&항공 특가할인 </div>\r\n");
      out.write("        <div id=\"best_price\">\r\n");
      out.write("            남은 시간 <font color=\"red\" size=\"5\"><b>47일</b></font>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"box6\">\r\n");
      out.write("            마카오<br>\r\n");
      out.write("            <div id=\"best_price2\">\r\n");
      out.write("                206,793 <font size=\"5\"><b> >  113,707 </b></font>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <br>\r\n");
      out.write("    <div id=\"best3\" onclick=\"location.href='main_img9.jsp'\">\r\n");
      out.write("        <img id=\"box5\" src=\"main/돈키호테.png\">\r\n");
      out.write("        <div id=\"best_korname\"> 일본 돈키호테 할인쿠폰 </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"best3\" onclick=\"location.href='main_img10.jsp'\">\r\n");
      out.write("        <img id=\"box5\" src=\"main/간사이 공항.png\">\r\n");
      out.write("        <div id=\"best_korname\"> 간사이 국제공항 (KIX) 면세점 5% 할인쿠폰 </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>\r\n");
      out.write("    <font face=\"함초롬돋움\" size=\"7\"> 12월 여행도시 </font>\r\n");
      out.write("    <font face=\"함초롬돋움\" size=\"5\"> 투어메이트가 추천하는 호주 </font>\r\n");
      out.write("    <div id=\"aus_image\">\r\n");
      out.write("        <img id=\"recommand1\" src=\"main/호주1.jpg\">\r\n");
      out.write("        <img id=\"recommand1\" src=\"main/호주2.png\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <br><br>\r\n");
      out.write("    <div id=\"aus_image\">\r\n");
      out.write("        <img id=\"recommand2\" src=\"main/호주3.jpg\">\r\n");
      out.write("        <img id=\"recommand2\" src=\"main/호주5.jpg\">\r\n");
      out.write("        <img id=\"recommand2\" src=\"main/호주4.jpg\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <br><br><br>\r\n");
      out.write("   \r\n");
      out.write("   <!-- 회사 정보와 약속을 포함한 Footer.jsp 파일을 include -->\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
