/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-12-07 14:19:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class 티켓투어_005f한국_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("\t\t<title>투어메이트</title>\r\n");
      out.write("\t\t<script src=\"http://code.jquery.com/jquery-1.10.1.js\"></script>\r\n");
      out.write("\t\t<!-- 외부 스타일시트 참조 -->\r\n");
      out.write("  \t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"티켓투어.css\">\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<!-- 제목+메뉴바를 포함한 Header.jsp 파일을 include -->\r\n");
      out.write(" \t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/63빌딩.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/63빌딩2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/63빌딩3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 63빌딩 아쿠아리움 + 전망대 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 31,000원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/카멜리아힐.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/카멜리아힐2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/카멜리아힐3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\">[방송촬영인기관광지] 카멜리아힐</div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 6,500원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/퍼시픽랜드.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/퍼시픽랜드2.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 퍼시픽랜드 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 9,000원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/레일바이크.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/레일바이크2.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\">레일바이크</div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 9,800원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/넥슨컴퓨터박물관.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/넥슨컴퓨터박물관2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/넥슨컴퓨터박물관3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\">넥슨컴퓨터박물관</div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 7,500원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/남산타워.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/남산타워2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/남산타워3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> [방송촬영인기관광지] 남산타워 케이블카 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 8,000원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/김녕미로공원.gif\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/김녕미로공원2.gif\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\">[방송촬영인기관광지] 김녕미로공원</div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 3,000원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/마라도여객선.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/마라도여객선2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/마라도여객선3.JPG\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\">마라도 여객선</div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 16,000원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/테디베어뮤지엄.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/테디베어뮤지엄2.dib\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_korea/테디베어뮤지엄3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> [방송촬영인기관광지] 테디베어뮤지엄 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\">9,200원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 회사 정보와 약속을 포함한 Footer.jsp 파일을 include -->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
