/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-12-05 03:01:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class 티켓투어_005f대만_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("\t\t<title>투어메이트</title>\r\n");
      out.write("\t\t<script src=\"http://code.jquery.com/jquery-1.10.1.js\"></script>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\tdiv{font-family:\"함초롬돋움\";}\r\n");
      out.write("\t\tdiv.header1{\r\n");
      out.write("\t\t\twidth:30%;\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t\tmargin-left:25px;\r\n");
      out.write("\t\t\tmargin-top:50px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv.header2{\r\n");
      out.write("\t\t\twidth:33%;\r\n");
      out.write("\t\t\theight:60px;\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t\tcolor:black;\r\n");
      out.write("\t\t\tmargin-left:40px;\r\n");
      out.write("\t\t\tmargin-top:15px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv.header2 > a {\r\n");
      out.write("\t\t\tcolor:black; text-decoration:none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv.header3{\r\n");
      out.write("\t\t\twidth:31%;\r\n");
      out.write("\t\t\theight:50px;\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t\tmargin-right:10px;\r\n");
      out.write("\t\t\tmargin-top:65px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv.footer{\r\n");
      out.write("\t\t\twidth:99%;\r\n");
      out.write("\t\t\theight:220px;\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t\tbackground-color:#FF8000;\r\n");
      out.write("\t\t\tcolor:white;\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t\tpadding-top:10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv.promise{\r\n");
      out.write("\t\t\twidth:20%;\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t\theight:140px;\r\n");
      out.write("\t\t\tbackground-color:#FF8000;\r\n");
      out.write("\t\t\tcolor:white;\r\n");
      out.write("\t\t\tfont-size:15px;\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t\tpadding-top:5px;\r\n");
      out.write("\t\t\tpadding-left:55px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv.footer2{\r\n");
      out.write("\t\t\twidth:45%;\r\n");
      out.write("\t\t\theight:40px;\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t\tfont-size:28px;\r\n");
      out.write("\t\t\tbackground-color:#FF8000;\r\n");
      out.write("\t\t\tcolor:white;\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t\tpadding-top:5px;\r\n");
      out.write("\t\t\tmargin-left:2%;\r\n");
      out.write("\t\t\tmargin-right:3%;\r\n");
      out.write("\t\t\tmargin-top:40px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv.footer3{\r\n");
      out.write("\t\t\twidth:45%;\r\n");
      out.write("\t\t\theight:35px;\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t\tfont-size:28px;\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t\tpadding-top:4px;\r\n");
      out.write("\t\t\tmargin-left:34px;\r\n");
      out.write("\t\t\tmargin-right:34px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv.footer4{\r\n");
      out.write("\t\t\twidth:45%;\r\n");
      out.write("\t\t\theight:150px;\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t\tfont-size:18px;\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t\tpadding-top:15px;\r\n");
      out.write("\t\t\tmargin-top:2px;\r\n");
      out.write("\t\t\tmargin-left:34px;\r\n");
      out.write("\t\t\tmargin-right:34px;\r\n");
      out.write("\t\t\tborder-width: 1px;\r\n");
      out.write("            border-style : dotted;\r\n");
      out.write("            border-color : #FF8000;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdiv.footer5{\r\n");
      out.write("\t\t\twidth:99%;\r\n");
      out.write("\t\t\theight:170px;\r\n");
      out.write("\t\t\tfont-size:15px;\r\n");
      out.write("\t\t\tbackground-color:#424242;\r\n");
      out.write("\t\t\tcolor:white;\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t\tpadding-top:15px;\r\n");
      out.write("\t\t\tmargin-top:40px;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t .menubar {\r\n");
      out.write("          background: #FF8000;\r\n");
      out.write("          display: inline-block;\r\n");
      out.write("           width: 100%;\r\n");
      out.write("      \t}\r\n");
      out.write("      \t.main { margin: 0; padding: 0; font-size : 19px; }\r\n");
      out.write("      \t.main li {\r\n");
      out.write("         \tpadding:0% 3% 0% 3%;\r\n");
      out.write("           float: left;\r\n");
      out.write("           list-style:none;\r\n");
      out.write("           position: relative;\r\n");
      out.write("      \t}\r\n");
      out.write("      \t.main li:first-child { margin-left: 10%; }\r\n");
      out.write("      \t.main li:hover { background: #984807; }\r\n");
      out.write("      \t.main a {\r\n");
      out.write("           color: white;\r\n");
      out.write("           display: block;\r\n");
      out.write("           padding: 10px 20px;\r\n");
      out.write("           text-decoration: none;\r\n");
      out.write("     \t}\r\n");
      out.write("      \t.main ul {\r\n");
      out.write("           background: white;\r\n");
      out.write("           display: none;\r\n");
      out.write("           padding: 0;\r\n");
      out.write("           position: absolute;\r\n");
      out.write("           left: 0;\r\n");
      out.write("           top: 100%;\r\n");
      out.write("           z-index: 2;\r\n");
      out.write("           width: 200px;\r\n");
      out.write("      \t}\r\n");
      out.write("      \t.main ul li { float: none; margin-left: 10%; }\r\n");
      out.write("      \t.main ul a { color: #984807; }\r\n");
      out.write("     \t.main ul li:hover { background: white; }\r\n");
      out.write("     \t.main ul li:hover>a { color: #FF8000; }\r\n");
      out.write("\r\n");
      out.write("\t\t#content {\r\n");
      out.write("\t\t\twidth:27%;\r\n");
      out.write("\t\t\theight:310px;\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t\tborder:0.2px solid gray;\r\n");
      out.write("\t\t\tbackground-color: #F2F2F2;\r\n");
      out.write("\t\t\tmargin: 2% 3% 2% 3%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#box {\r\n");
      out.write("\t\t\twidth:100%;\r\n");
      out.write("\t\t\theight:220px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#name {\r\n");
      out.write("\t\t\tfont-size:18px;\r\n");
      out.write("\t\t\ttext-align:left;\r\n");
      out.write("\t\t\tcolor:black;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#price {\r\n");
      out.write("\t\t\tfont-size:24px;\r\n");
      out.write("\t\t\ttext-align:right;\r\n");
      out.write("\t\t\tcolor:black;\r\n");
      out.write("\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#fo{width:60px; height:60px; padding:10px 70px 5px 70px;}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"header1\">\r\n");
      out.write("\t\t\t<input type=\"text\" size=30></input>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"검색\"></input>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<a href=\"투어메이트.html\">\r\n");
      out.write("\t\t<div class=\"header2\">\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t<font face=\"HYHeadLine\" size=\"7\">Tourmate</font><br>\r\n");
      out.write("\t\t\t<font face=\"함초롬돋움\" size=\"4\">믿을 수 있는 여행 친구, 투어메이트</font>\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<div class=\"header3\">\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t<font face=\"함초롬돋움\" size=\"3\">로그인 | 회원가입 | 이벤트</font>\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--상단 메뉴바와 하위 메뉴-->\r\n");
      out.write("    <script src=\"//code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("   <script>\r\n");
      out.write("   $(function(){\r\n");
      out.write("        $(\".main li\").hover(function(){\r\n");
      out.write("          $('ul:first',this).show();\r\n");
      out.write("        }, function(){\r\n");
      out.write("          $('ul:first',this).hide();\r\n");
      out.write("        });\r\n");
      out.write("   });\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("    <div class=\"menubar\">\r\n");
      out.write("        <ul class=\"main\">\r\n");
      out.write("            <li>\r\n");
      out.write("                 <a href=\"#\">여행 정보</a>\r\n");
      out.write("                 <ul>\r\n");
      out.write("                  <li><a href=\"인기_여행_도시.jsp\">인기 여행 도시</a></li>\r\n");
      out.write("                  <li><a href=\"#\">여행 준비</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">커뮤니티</a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"여행_후기.jsp\">여행 후기</a></li>\r\n");
      out.write("                    <li><a href=\"#\">맛집 추천</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">티켓/투어</a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"티켓투어_한국.jsp\">한국</a></li>\r\n");
      out.write("                    <li><a href=\"티켓투어_홍콩.jsp\">홍콩</a></li>\r\n");
      out.write("                    <li><a href=\"티켓투어_일본.jsp\">일본</a></li>\r\n");
      out.write("                    <li><a href=\"티켓투어_싱가포르.jsp\">싱가포르</a></li>\r\n");
      out.write("                    <li><a href=\"티켓투어_대만.jsp\">대만</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <li><a href=\"항공.jsp\">항공</a></li>\r\n");
      out.write("            <li><a href=\"호텔.jsp\">호텔</a></li>\r\n");
      out.write("            <li><a href=\"렌터카.jsp\">렌터카</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/101타워.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/101타워2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/101타워3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 타이페이 101타워 전망대 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 18,300원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/티엔라이.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/티엔라이2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/티엔라이3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 티엔라이 노천 온천 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 19,000원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/육복촌.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/육복촌2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/육복촌3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 육복촌(레오푸 빌리지) </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 21,000원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/경극.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/경극2.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 경극-타이페이 아이(Taipei Eye) </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 6,300원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/소인국테마파크.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/소인국테마파크2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/소인국테마파크3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 타오위안 소인국 테마파크 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 16,010원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/고속철도.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/고속철도2.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 고속철도 THSR패스 3일권(연속) </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 74,000원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/고궁박물관.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/고궁박물관2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/고궁박물관3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 국립 고궁박물관 + 순이 원주민박물관 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 11,800원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/초콜릿원더랜드.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/초콜릿원더랜드2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/초콜릿원더랜드3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 단수이 월드 초콜릿 원더랜드 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 9,000원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/스프링시티온천.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/스프링시티온천2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Taiwan/스프링시티온천3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 스프링시티 노천 온천 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\">24,000원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer\">\r\n");
      out.write("\t\t\t<font size=\"6\">여행자분들에게 약속드립니다.</font><br>\r\n");
      out.write("\t\t\t<div class=\"promise\">\r\n");
      out.write("\t\t\t\t<img id=\"fo\" src=\"main/footer 그림1.png\"><br>\r\n");
      out.write("\t\t\t\t수익을 위해 여행자를<br>\r\n");
      out.write("\t\t\t\t속이며, 잘못된 정보를<br>\r\n");
      out.write("\t\t\t\t추천하지 않겠습니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"promise\">\r\n");
      out.write("\t\t\t\t<img id=\"fo\" src=\"main/footer 그림2.png\"><br>\r\n");
      out.write("\t\t\t\t자유여행자 분들에게<br>\r\n");
      out.write("\t\t\t\t꼭 필요한 정보만 엄선하고<br>\r\n");
      out.write("\t\t\t\t객관성을 유지하겠습니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"promise\">\r\n");
      out.write("\t\t\t\t<img id=\"fo\" src=\"main/footer 그림3.png\"><br>\r\n");
      out.write("\t\t\t\t여행자분들의 제안과<br>\r\n");
      out.write("\t\t\t\t신고를 흘려버리지 않고<br>\r\n");
      out.write("\t\t\t\t서비스에 적극 반영하겠습니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"promise\">\r\n");
      out.write("\t\t\t\t<img id=\"fo\" src=\"main/footer 그림4.png\"><br>\r\n");
      out.write("\t\t\t\t여행가기 전에 믿고<br>\r\n");
      out.write("\t\t\t\t방문할 수 있는 서비스를<br>\r\n");
      out.write("\t\t\t\t제공하도록 노력하겠습니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div class=\"footer2\">고객 센터</div>\r\n");
      out.write("\t\t<div class=\"footer2\">은행 정보</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div class=\"footer3\">1688-1234</div>\r\n");
      out.write("\t\t<div class=\"footer3\">예금주 : (주)투어메이트</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div class=\"footer4\">\r\n");
      out.write("\t\t\t<font color=\"brown\" size=\"4\">근무 시간 안내</font><br><br>\r\n");
      out.write("\t\t\t평일 9:00 ~ 19:00(고객센터)<br>\r\n");
      out.write("\t\t\t토요일 10:00 ~ 16:00(고객센터)<br>\r\n");
      out.write("\t\t\t점심시간 12:00 ~ 13:00<br>\r\n");
      out.write("\t\t\t일요일 및 공휴일은 휴무입니다.<br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer4\"><br>\r\n");
      out.write("\t\t\t국민 : 12345-123456<br>\r\n");
      out.write("\t\t\t신한 : 123-456-789012<br>\r\n");
      out.write("\t\t\t하나 : 123-123456-78901<br>\r\n");
      out.write("\t\t\t우리 : 1234-567-890123<br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer5\">\r\n");
      out.write("\t\t\t상호명 : 투어메이트 | 대표 : 이주영, 고노윤 | 대표전화 : 1688-1234<br>\r\n");
      out.write("\t\t\t주소 : 서울특별시 중구 필동로 1길 123 | <br>\r\n");
      out.write("\t\t\t사업자 등록 번호 : 123-45-67890 |<br>\r\n");
      out.write("\t\t\t통신판매업신고 : 제2017-1234동-5678호<br>\r\n");
      out.write("\t\t\t이메일 : tourmate@naver.com<br>\r\n");
      out.write("\t\t\tFAX : 123-4567-8901<br><br>\r\n");
      out.write("\t\t\tCOPYRIGHT(C) ALL RIGHTS RESERVED.<br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
