/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-12-07 12:54:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class 티켓투어_005f홍콩_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("\t\t<title>투어메이트</title>\r\n");
      out.write("\t\t<script src=\"http://code.jquery.com/jquery-1.10.1.js\"></script>\r\n");
      out.write("\t\t<!-- 외부 스타일시트 참조 -->\r\n");
      out.write("  \t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"티켓투어.css\">\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<!-- 제목+메뉴바를 포함한 Header.jsp 파일을 include -->\r\n");
      out.write(" \t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/디즈니랜드.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/디즈니랜드2.wdp\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/디즈니랜드3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> [방송촬영인기관광지] 디즈니랜드 1일권 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 79,900원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/피크트램.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/피크트램2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/피크트램3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 피크트램 & 스카이테라스</div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 9,000원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/터보젯페리.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/터보젯페리2.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> [홍콩->마카오]터보젯페리 주간 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 25,470원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/오션파크.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/오션파크2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/오션파크3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 오션파크 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 58,000원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/마담투소.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/마담투소2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/마담투소3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> [방송촬영인기관광지] 마담투소 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 27,680원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/스카이.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/스카이1002.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/스카이1003.png\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 스카이100 야간권 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 12,180원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/고속전철.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/고속전철2.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> AEL 공항 고속전철 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 9,750원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/빅버스.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/빅버스2.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 빅버스 투어(클래식, 프리미엄) </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 54,250원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/아이벤처카드.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_hongkong/아이벤처카드2.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 아이벤처 카드(관광지 패스) </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\">9,200원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 회사 정보와 약속을 포함한 Footer.jsp 파일을 include -->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
