/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-12-05 03:16:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class 티켓투어_005f싱가포르_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("\t\t<title>투어메이트</title>\r\n");
      out.write("\t\t<script src=\"http://code.jquery.com/jquery-1.10.1.js\"></script>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t#content {\r\n");
      out.write("\t\t\twidth:27%;\r\n");
      out.write("\t\t\theight:310px;\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t\tborder:0.2px solid gray;\r\n");
      out.write("\t\t\tbackground-color: #F2F2F2;\r\n");
      out.write("\t\t\tmargin: 2% 3% 2% 3%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#box {\r\n");
      out.write("\t\t\twidth:100%;\r\n");
      out.write("\t\t\theight:220px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#name {\r\n");
      out.write("\t\t\tfont-size:18px;\r\n");
      out.write("\t\t\ttext-align:left;\r\n");
      out.write("\t\t\tcolor:black;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#price {\r\n");
      out.write("\t\t\tfont-size:24px;\r\n");
      out.write("\t\t\ttext-align:right;\r\n");
      out.write("\t\t\tcolor:black;\r\n");
      out.write("\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<!-- 제목+메뉴바를 포함한 Header.jsp 파일을 include -->\r\n");
      out.write(" \t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/유니버셜스튜디오.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/유니버셜스튜디오2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/유니버셜스튜디오3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 유니버셜 스튜디오(성인) </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 50,350원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/주롱새공원.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/주롱새공원2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/주롱새공원3.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/주롱새공원4.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 주롱새 공원 (트램 포함) </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 6,500원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/윙즈오브타임.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/윙즈오브타임2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/윙즈오브타임3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 윙즈 오브 타임 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 8,140원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/머라이언타워.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/머라이언타워2.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 싱가포르 머라이언 타워 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 6,300원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/마담투소.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/마담투소2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/마담투소3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 마담투소 & IOS LIVE </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 16,010원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/아쿠아리움.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/아쿠아리움2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/아쿠아리움3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 싱가폴 SEA 아쿠아리움 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 17,510원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/내셔널갤러리.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/내셔널갤러리2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/내셔널갤러리3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 내셔널 갤러리 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 12,130원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/스카이라인.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/스카이라인2.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 스카이라인 루지 & 스카이라이드 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\"> 9,310원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\" scrollamount=\"10\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/가든스바이더베이.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/가든스바이더베이2.jpg\">\r\n");
      out.write("\t\t\t<img id=\"box\" src=\"3_Singapore/가든스바이더베이3.jpg\">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t\t<div id=\"name\"> 가든스 바이 더 베이 </div><br>\r\n");
      out.write("\t\t\t<div id=\"price\">17,100원 </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 회사 정보와 약속을 포함한 Footer.jsp 파일을 include -->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
