/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-12-07 09:48:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class 항공_005fresult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("utf-8");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("   <head>\r\n");
      out.write("      <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("      <title>투어메이트</title>\r\n");
      out.write("      <script src=\"http://code.jquery.com/jquery-1.10.1.js\"></script>\r\n");
      out.write("      <style>\r\n");
      out.write("      .mainbox { padding-left:15%; }\r\n");
      out.write("      \r\n");
      out.write("      .whitebox {\r\n");
      out.write("         position:absolute;\r\n");
      out.write("         top:280px;\r\n");
      out.write("         left:275px;\r\n");
      out.write("         height:370px;\r\n");
      out.write("         width:900px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("   \t  #flightbox {\r\n");
      out.write("   \t  \t width:100%;\r\n");
      out.write("   \t  \t height:40px;\r\n");
      out.write("   \t  \t background:white;\r\n");
      out.write("   \t  }\r\n");
      out.write("   \t  \r\n");
      out.write("   \t  #flightbox2 {\r\n");
      out.write("   \t  \tfloat:left;\r\n");
      out.write("   \t  \t width:65%;\r\n");
      out.write("   \t  \t height:180px;\r\n");
      out.write("   \t  \t padding-right:20.5px;\r\n");
      out.write("   \t  \t background:white;\r\n");
      out.write("   \t  \t opacity:0.9;\r\n");
      out.write("   \t  }\r\n");
      out.write("   \t  \r\n");
      out.write("   \t  #flightbox3 {\r\n");
      out.write("   \t  \t float:right;\r\n");
      out.write("   \t  \t width:32.7%;\r\n");
      out.write("   \t  \t height:180px;\r\n");
      out.write("   \t  \t background:white;\r\n");
      out.write("   \t  \t opacity:0.9;\r\n");
      out.write("   \t  }\r\n");
      out.write("   \t  \r\n");
      out.write("   \t  #flightbox4 {\r\n");
      out.write("   \t  \t width:880px;\r\n");
      out.write("   \t  \t height:130px;\r\n");
      out.write("   \t  \t margin-top:200px;\r\n");
      out.write("   \t  \t padding-right:20px;\r\n");
      out.write("   \t  \t background:white;\r\n");
      out.write("   \t  \t opacity:0.9;\r\n");
      out.write("   \t  }\r\n");
      out.write("   \t  \r\n");
      out.write("   \t  #age {\r\n");
      out.write("   \t  \twidth:30%;\r\n");
      out.write("   \t  \theight:160px;\r\n");
      out.write("   \t  \tfloat:left;\r\n");
      out.write("   \t  \tmargin: 10px 8px 8px 0px;\r\n");
      out.write("   \t  }\r\n");
      out.write("   \t  \r\n");
      out.write("      #bgimg {\r\n");
      out.write("         width:1010px;\r\n");
      out.write("         height:450px;\r\n");
      out.write("         margin-right: 15%;\r\n");
      out.write("         margin-bottom: 3%;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      #humanimg {\r\n");
      out.write("      \twidth:50%;\r\n");
      out.write("      \tpadding-left:20px;\r\n");
      out.write("      \theight:85px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      #humanimg2 {\r\n");
      out.write("      \twidth:45%;\r\n");
      out.write("      \tpadding-left:20px;\r\n");
      out.write("      \tpadding-top:15px;\r\n");
      out.write("      \theight:65px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      #size {\r\n");
      out.write("      \twidth:40px;\r\n");
      out.write("      \theight:40px;\r\n");
      out.write("      \tmargin-left:8px;\r\n");
      out.write("      \tmargin-right:8px;\r\n");
      out.write("      \tfloat:left;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      a:link {text-decoration: underline; color: black;}\r\n");
      out.write("\t  a:visited {text-decoration: none; color: black;}\r\n");
      out.write("\t  a:hover {text-decoration: underline; color: #FF8000;}\r\n");
      out.write("      </style>\r\n");
      out.write("   </head>\r\n");
      out.write("   <body>\r\n");
      out.write("    <!-- 제목+메뉴바를 포함한 Header.jsp 파일을 include -->\r\n");
      out.write(" \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("    <div class=\"mainbox\">\r\n");
      out.write("    <p><h2>최저가 항공권 검색</h2></p>\r\n");
      out.write("    <img id=\"bgimg\" src=\"4_flight/공항.jpg\">   \r\n");
      out.write("    </div>\r\n");
      out.write("   \t");
 
   		String start=request.getParameter("start");
   		String end=request.getParameter("end");
   		String checkin=request.getParameter("checkin");
   		String checkout=request.getParameter("checkout");
   		String adult=request.getParameter("adult");
   		String kid=request.getParameter("kid");
   		String baby=request.getParameter("baby");
   		
   		int a=Integer.parseInt(adult);
   		int b=Integer.parseInt(kid);
   		int c=Integer.parseInt(baby);
   	
      out.write("\r\n");
      out.write("   \t\r\n");
      out.write("   \t<div class=\"whitebox\">\r\n");
      out.write("   \t\t<div id=\"flightbox\">\r\n");
      out.write("   \t\t<b><img id=\"size\" src=\"4_flight/비행기아이콘.jpg\"><font size=\"5\">항공편</font></b>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t\t<div id=\"flightbox2\"> \r\n");
      out.write("   \t\t\t<p><h2>&nbsp;&nbsp;출발지 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.start}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2></p>\r\n");
      out.write("   \t\t\t<p><h2>&nbsp;&nbsp;도착지 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.end}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2></p>\r\n");
      out.write("   \t\t\t<p><h2>&nbsp;&nbsp;기간 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.checkin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('~');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.checkout}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2></p>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t\t<div id=\"flightbox3\"> \r\n");
      out.write("   \t\t\t<font size=\"4\">\r\n");
      out.write("   \t\t\t<div id=\"age\">\r\n");
      out.write("   \t\t\t\t<img id=\"humanimg\" src=\"4_flight/어른.jpg\"><br>\r\n");
      out.write("   \t\t\t\t<center>어른<br>");
      out.print( a);
      out.write("명</center>\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("   \t\t\t<div id=\"age\">\r\n");
      out.write("   \t\t\t\t<img id=\"humanimg2\" src=\"4_flight/아이.jpg\">\r\n");
      out.write("   \t\t\t\t<center>아이<br>");
      out.print( b);
      out.write("명</center>\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("   \t\t\t<div id=\"age\">\r\n");
      out.write("   \t\t\t\t<img id=\"humanimg2\" src=\"4_flight/유아.png\">\r\n");
      out.write("   \t\t\t\t<center>유아<br>");
      out.print( c);
      out.write("명</center>\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("   \t\t\t</font>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t\t<div id=\"flightbox4\">\r\n");
      out.write("   \t\t\t<p><h2>&nbsp;&nbsp;최저가 : 549,277원</h2></p>\r\n");
      out.write("   \t\t\t<h4>&nbsp;&nbsp;<a href = \"ok.jsp\">아시아나 : 직항 3시간 38분 소요</a></h4>\r\n");
      out.write("   \t\t\t<h4>&nbsp;&nbsp;<a href = \"ok.jsp\">대한항공 : 직항 4시간 소요</a></h4>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t</div>\r\n");
      out.write("\t<!-- 회사 정보와 약속을 포함한 Footer.jsp 파일을 include -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
