/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-12-07 14:34:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class 항공_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("   <head>\r\n");
      out.write("      <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("      <title>투어메이트</title>\r\n");
      out.write("      <script src=\"http://code.jquery.com/jquery-1.10.1.js\"></script>\r\n");
      out.write("   <!-- 외부 스타일시트 참조 -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"항호렌.css\">\r\n");
      out.write("\r\n");
      out.write("   </head>\r\n");
      out.write("   <body>\r\n");
      out.write("    <!-- 제목+메뉴바를 포함한 Header.jsp 파일을 include -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("   <div class=\"mainbox\">\r\n");
      out.write("   <p><h2>최저가 항공권 검색</h2></p>\r\n");
      out.write("   <img id=\"bgimg\" src=\"4_flight/비행기날개.jpg\">   \r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <!-- 달력 만들기 -->\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("   <script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js\"></script>\r\n");
      out.write("   <script src=\"//code.jquery.com/ui/1.8.18/jquery-ui.min.js\"></script>\r\n");
      out.write("   <script>\r\n");
      out.write("     $( function() {\r\n");
      out.write("       $(\"#datepicker1, #datepicker2\").datepicker({\r\n");
      out.write("          dateFormat: 'yy년 mm월 dd일'\r\n");
      out.write("       });\r\n");
      out.write("     } );\r\n");
      out.write("     </script>   \r\n");
      out.write("   \r\n");
      out.write("   <div class=\"whitebox\">\r\n");
      out.write("   <form action=\"항공_result.jsp\" method=\"post\">\r\n");
      out.write("        <br>\r\n");
      out.write("      <div class=\"input1\">\r\n");
      out.write("      <b><font size=3>출발지</font></b>\r\n");
      out.write("      <input class=\"check1\" type=\"text\" name=\"start\" placeholder=\"도시명\" >⟷\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"input2\">\r\n");
      out.write("      <b><font size=3>도착지</font></b>\r\n");
      out.write("      <input class=\"check2\" type=\"text\" name=\"end\" placeholder=\"도시명\" >\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"input_checkin\">\r\n");
      out.write("      <b><font size=3>체크인</font></b><br>\r\n");
      out.write("      <input class=\"check3\" id=\"datepicker1\" type=\"text\" name=\"checkin\" placeholder=\"날짜 선택\" >\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"input_checkout\">\r\n");
      out.write("      <b><font size=3>체크아웃</font></b><br>\r\n");
      out.write("      <input class=\"check3\" id=\"datepicker2\" type=\"text\" name=\"checkout\" placeholder=\"날짜 선택\" >\r\n");
      out.write("      </div>\r\n");
      out.write("        \r\n");
      out.write("      <div class=\"input3\">\r\n");
      out.write("      <b><font size=3>인원</font></b>\r\n");
      out.write("      <select class=\"text1\" name=\"adult\">\r\n");
      out.write("         <option value=\"1\">성인1명</option>\r\n");
      out.write("         <option value=\"2\">성인2명</option>\r\n");
      out.write("         <option value=\"3\">성인3명</option>\r\n");
      out.write("         <option value=\"4\">성인4명</option>\r\n");
      out.write("         <option value=\"5\">성인5명</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input3\">\r\n");
      out.write("      <br>\r\n");
      out.write("      <select class=\"text1\" name=\"kid\">\r\n");
      out.write("         <option value=\"0\">아동0명</option>\r\n");
      out.write("         <option value=\"1\">아동1명</option>\r\n");
      out.write("         <option value=\"2\">아동2명</option>\r\n");
      out.write("         <option value=\"3\">아동3명</option>\r\n");
      out.write("         <option value=\"4\">아동4명</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input3\">\r\n");
      out.write("      <br>\r\n");
      out.write("      <select class=\"text1\" name=\"baby\">\r\n");
      out.write("         <option value=\"0\">유아0명</option>\r\n");
      out.write("         <option value=\"1\">유아1명</option>\r\n");
      out.write("         <option value=\"2\">유아2명</option>\r\n");
      out.write("         <option value=\"3\">유아3명</option>\r\n");
      out.write("         <option value=\"4\">유아4명</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"flight_bottom\">\r\n");
      out.write("      <button type=\"reset\" class=\"reset\">초기화</button>\r\n");
      out.write("      <input type=\"submit\" value=\"검색\" class=\"submit\">\r\n");
      out.write("      </div>\r\n");
      out.write("   </form>\r\n");
      out.write("   <br>\r\n");
      out.write("   <b><font size=\"3\" color=\"white\">왕복 기준*</font></b>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- 회사 정보와 약속을 포함한 Footer.jsp 파일을 include -->\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
